# Seznam barev pro gradient aplikaci s názvy
color_palette = [
    {"name": "Red", "hex": "#FF0000"},
    {"name": "Lime", "hex": "#00FF00"},
    {"name": "Blue", "hex": "#0000FF"},
    {"name": "Yellow", "hex": "#FFFF00"},
    {"name": "Magenta", "hex": "#FF00FF"},
    {"name": "Cyan", "hex": "#00FFFF"},
    {"name": "Orange", "hex": "#FFA500"},
    {"name": "Purple", "hex": "#800080"},
    {"name": "Pink", "hex": "#FFC0CB"},
    {"name": "Brown", "hex": "#A52A2A"},
    {"name": "Gray", "hex": "#808080"},
    {"name": "Black", "hex": "#000000"},
    {"name": "White", "hex": "#FFFFFF"},
    {"name": "Silver", "hex": "#C0C0C0"},
    {"name": "Maroon", "hex": "#800000"},
    {"name": "Olive", "hex": "#808000"},
    {"name": "Green", "hex": "#008000"},
    {"name": "Teal", "hex": "#008080"},
    {"name": "Navy", "hex": "#000080"},
    {"name": "Coral", "hex": "#FF6347"},
    {"name": "Tomato", "hex": "#FF4500"},
    {"name": "Hot Pink", "hex": "#FF69B4"},
    {"name": "Crimson", "hex": "#DC143C"},
    {"name": "Firebrick", "hex": "#B22222"},
    {"name": "Dark Red", "hex": "#8B0000"},
    {"name": "Deep Pink", "hex": "#FF1493"},
    {"name": "Violet", "hex": "#8A2BE2"},
    {"name": "Indigo", "hex": "#4B0082"},
    {"name": "Slate Blue", "hex": "#483D8B"},
    {"name": "Medium Slate Blue", "hex": "#7B68EE"},
    {"name": "Medium Purple", "hex": "#9370DB"},
    {"name": "Medium Orchid", "hex": "#BA55D3"},
    {"name": "Plum", "hex": "#DDA0DD"},
    {"name": "Thistle", "hex": "#D8BFD8"},
    {"name": "Lavender", "hex": "#E6E6FA"},
    {"name": "Light Blue", "hex": "#ADD8E6"},
    {"name": "Light Green", "hex": "#90EE90"},
    {"name": "Light Yellow", "hex": "#FFFFE0"},
    {"name": "Light Cyan", "hex": "#E0FFFF"},
    {"name": "Light Pink", "hex": "#FFB6C1"},
    {"name": "Light Salmon", "hex": "#FFA07A"},
    {"name": "Light Coral", "hex": "#F08080"},
    {"name": "Dark Orange", "hex": "#FF8C00"},
    {"name": "Gold", "hex": "#FFD700"},
    {"name": "Khaki", "hex": "#F0E68C"},
    {"name": "Dark Khaki", "hex": "#BDB76B"},
    {"name": "Yellow Green", "hex": "#9ACD32"},
    {"name": "Lawn Green", "hex": "#7CFC00"},
    {"name": "Chartreuse", "hex": "#7FFF00"},
    {"name": "Lime Green", "hex": "#32CD32"},
    {"name": "Forest Green", "hex": "#228B22"},
    {"name": "Dark Green", "hex": "#006400"},
    {"name": "Medium Sea Green", "hex": "#3CB371"},
    {"name": "Sea Green", "hex": "#2E8B57"},
    {"name": "Dark Sea Green", "hex": "#8FBC8F"},
    {"name": "Aquamarine", "hex": "#7FFFD4"},
    {"name": "Medium Aquamarine", "hex": "#66CDAA"},
    {"name": "Light Sea Green", "hex": "#20B2AA"},
    {"name": "Dark Cyan", "hex": "#008B8B"},
    {"name": "Turquoise", "hex": "#40E0D0"},
    {"name": "Medium Turquoise", "hex": "#48D1CC"},
    {"name": "Dark Turquoise", "hex": "#00CED1"},
    {"name": "Deep Sky Blue", "hex": "#00BFFF"},
    {"name": "Dodger Blue", "hex": "#1E90FF"},
    {"name": "Royal Blue", "hex": "#4169E1"},
    {"name": "Medium Blue", "hex": "#0000CD"},
    {"name": "Dark Blue", "hex": "#00008B"},
    {"name": "Midnight Blue", "hex": "#191970"},
    {"name": "Dark Slate Blue", "hex": "#483D8B"},
    {"name": "Dark Violet", "hex": "#9400D3"},
    {"name": "Dark Magenta", "hex": "#8B008B"},
    {"name": "Dark Orchid", "hex": "#9932CC"},
    {"name": "Saddle Brown", "hex": "#8B4513"},
    {"name": "Sienna", "hex": "#A0522D"},
    {"name": "Chocolate", "hex": "#D2691E"},
    {"name": "Sandy Brown", "hex": "#F4A460"},
    {"name": "Wheat", "hex": "#F5DEB3"},
    {"name": "Beige", "hex": "#F5F5DC"},
    {"name": "Linen", "hex": "#FAF0E6"},
    {"name": "Antique White", "hex": "#FAEBD7"},
    {"name": "Papaya Whip", "hex": "#FFEFD5"},
    {"name": "Moccasin", "hex": "#FFE4B5"},
    {"name": "Peach Puff", "hex": "#FFDAB9"},
    {"name": "Misty Rose", "hex": "#FFE4E1"},
    {"name": "Lavender Blush", "hex": "#FFF0F5"},
    {"name": "Snow", "hex": "#FFFAFA"},
    {"name": "Ivory", "hex": "#FFFFF0"},
    {"name": "Azure", "hex": "#F0FFFF"},
    {"name": "Alice Blue", "hex": "#F0F8FF"},
    {"name": "Ghost White", "hex": "#F8F8FF"},
    {"name": "Honeydew", "hex": "#F0FFF0"},
    {"name": "Mint Cream", "hex": "#F5FFFA"},
    {"name": "Sea Shell", "hex": "#FFF5EE"},
    {"name": "Old Lace", "hex": "#FDF5E6"},
    {"name": "Floral White", "hex": "#FFFAF0"},
    {"name": "Cornsilk", "hex": "#FFF8DC"},
    {"name": "Lemon Chiffon", "hex": "#FFFACD"},
    {"name": "Light Goldenrod", "hex": "#EEDD82"},
    {"name": "Light Yellow", "hex": "#FFFFE0"},
    {"name": "Pale Goldenrod", "hex": "#EEE8AA"},
    {"name": "Dark Salmon", "hex": "#E9967A"},
    {"name": "Salmon", "hex": "#FA8072"},
    {"name": "Indian Red", "hex": "#CD5C5C"},
    {"name": "Rosy Brown", "hex": "#BC8F8F"},
    {"name": "Tan", "hex": "#D2B48C"},
    {"name": "Burlywood", "hex": "#DEB887"},
    {"name": "Peru", "hex": "#CD853F"},
    {"name": "Dark Goldenrod", "hex": "#B8860B"},
    {"name": "Goldenrod", "hex": "#DAA520"},
    {"name": "Medium Violet Red", "hex": "#C71585"},
    {"name": "Pale Violet Red", "hex": "#DB7093"},
    {"name": "Orchid", "hex": "#DA70D6"},
    {"name": "Fuchsia", "hex": "#FF00FF"},
    {"name": "Medium Violet Red", "hex": "#C71585"},
    {"name": "Deep Pink", "hex": "#FF1493"},
    {"name": "Hot Pink", "hex": "#FF69B4"},
    {"name": "Light Pink", "hex": "#FFB6C1"},
    {"name": "Pink", "hex": "#FFC0CB"},
    {"name": "Crimson", "hex": "#DC143C"},
    {"name": "Red", "hex": "#FF0000"},
    {"name": "Firebrick", "hex": "#B22222"},
    {"name": "Dark Red", "hex": "#8B0000"},
    {"name": "Coral", "hex": "#FF6347"},
    {"name": "Orange Red", "hex": "#FF4500"},
    {"name": "Orange", "hex": "#FFA500"},
    {"name": "Gold", "hex": "#FFD700"},
    {"name": "Yellow", "hex": "#FFFF00"},
    {"name": "Khaki", "hex": "#F0E68C"},
    {"name": "Pale Goldenrod", "hex": "#EEE8AA"},
    {"name": "Dark Khaki", "hex": "#BDB76B"},
    {"name": "Green Yellow", "hex": "#ADFF2F"},
    {"name": "Chartreuse", "hex": "#7FFF00"},
    {"name": "Lawn Green", "hex": "#7CFC00"},
    {"name": "Lime", "hex": "#00FF00"},
    {"name": "Lime Green", "hex": "#32CD32"},
    {"name": "Forest Green", "hex": "#228B22"},
    {"name": "Dark Green", "hex": "#006400"},
    {"name": "Olive Drab", "hex": "#6B8E23"},
    {"name": "Olive", "hex": "#808000"},
    {"name": "Dark Olive Green", "hex": "#556B2F"},
    {"name": "Medium Sea Green", "hex": "#3CB371"},
    {"name": "Sea Green", "hex": "#2E8B57"},
    {"name": "Light Sea Green", "hex": "#20B2AA"},
    {"name": "Dark Cyan", "hex": "#008B8B"},
    {"name": "Teal", "hex": "#008080"},
    {"name": "Aqua", "hex": "#00FFFF"},
    {"name": "Cyan", "hex": "#00FFFF"},
    {"name": "Light Cyan", "hex": "#E0FFFF"},
    {"name": "Pale Turquoise", "hex": "#AFEEEE"},
    {"name": "Aquamarine", "hex": "#7FFFD4"},
    {"name": "Turquoise", "hex": "#40E0D0"},
    {"name": "Medium Turquoise", "hex": "#48D1CC"},
    {"name": "Dark Turquoise", "hex": "#00CED1"},
    {"name": "Cadet Blue", "hex": "#5F9EA0"},
    {"name": "Steel Blue", "hex": "#4682B4"},
    {"name": "Light Steel Blue", "hex": "#B0C4DE"},
    {"name": "Powder Blue", "hex": "#B0E0E6"},
    {"name": "Light Blue", "hex": "#ADD8E6"},
    {"name": "Sky Blue", "hex": "#87CEEB"},
    {"name": "Light Sky Blue", "hex": "#87CEFA"},
    {"name": "Deep Sky Blue", "hex": "#00BFFF"},
    {"name": "Dodger Blue", "hex": "#1E90FF"},
    {"name": "Cornflower Blue", "hex": "#6495ED"},
    {"name": "Medium Slate Blue", "hex": "#7B68EE"},
    {"name": "Royal Blue", "hex": "#4169E1"},
    {"name": "Blue", "hex": "#0000FF"},
    {"name": "Medium Blue", "hex": "#0000CD"},
    {"name": "Dark Blue", "hex": "#00008B"},
    {"name": "Navy", "hex": "#000080"},
    {"name": "Midnight Blue", "hex": "#191970"},
    {"name": "Blue Violet", "hex": "#8A2BE2"},
    {"name": "Indigo", "hex": "#4B0082"},
    {"name": "Dark Slate Blue", "hex": "#483D8B"},
    {"name": "Slate Blue", "hex": "#6A5ACD"},
    {"name": "Medium Slate Blue", "hex": "#7B68EE"},
    {"name": "Medium Purple", "hex": "#9370DB"},
    {"name": "Blue Violet", "hex": "#8A2BE2"},
    {"name": "Dark Violet", "hex": "#9400D3"},
    {"name": "Dark Orchid", "hex": "#9932CC"},
    {"name": "Medium Orchid", "hex": "#BA55D3"},
    {"name": "Purple", "hex": "#800080"},
    {"name": "Dark Magenta", "hex": "#8B008B"},
    {"name": "Medium Violet Red", "hex": "#C71585"},
    {"name": "Deep Pink", "hex": "#FF1493"},
    {"name": "Hot Pink", "hex": "#FF69B4"},
    {"name": "Light Pink", "hex": "#FFB6C1"},
    {"name": "Pink", "hex": "#FFC0CB"},
    {"name": "Pale Violet Red", "hex": "#DB7093"},
    {"name": "Medium Violet Red", "hex": "#C71585"},
    {"name": "Violet Red", "hex": "#D02090"},
    {"name": "Magenta", "hex": "#FF00FF"},
    {"name": "Violet", "hex": "#EE82EE"},
    {"name": "Plum", "hex": "#DDA0DD"},
    {"name": "Orchid", "hex": "#DA70D6"},
    {"name": "Medium Orchid", "hex": "#BA55D3"},
    {"name": "Dark Orchid", "hex": "#9932CC"},
    {"name": "Dark Violet", "hex": "#9400D3"},
    {"name": "Blue Violet", "hex": "#8A2BE2"},
    {"name": "Purple", "hex": "#800080"},
    {"name": "Medium Purple", "hex": "#9370DB"},
    {"name": "Slate Blue", "hex": "#6A5ACD"},
    {"name": "Medium Slate Blue", "hex": "#7B68EE"},
    {"name": "Light Slate Blue", "hex": "#8470FF"},
    {"name": "Ghost White", "hex": "#F8F8FF"},
    {"name": "White Smoke", "hex": "#F5F5F5"},
    {"name": "Gainsboro", "hex": "#DCDCDC"},
    {"name": "Light Gray", "hex": "#D3D3D3"},
    {"name": "Silver", "hex": "#C0C0C0"},
    {"name": "Dark Gray", "hex": "#A9A9A9"},
    {"name": "Gray", "hex": "#808080"},
    {"name": "Dim Gray", "hex": "#696969"},
    {"name": "Light Slate Gray", "hex": "#778899"},
    {"name": "Slate Gray", "hex": "#708090"},
    {"name": "Dark Slate Gray", "hex": "#2F4F4F"},
    {"name": "Black", "hex": "#000000"}
]

# Pro zpětnou kompatibilitu - seznam jen hex kódů
colors = [color["hex"] for color in color_palette]